/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Reports that the process is up. Deliberately checks no dependencies; use /readyz to know whether the process can serve real traffic.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Reports whether the process can serve traffic (Postgres answers).
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Verifies the credential and opens a session. The access token (15 min JWT) and rotating refresh token are set as httpOnly cookies; the body carries only the user. Rate-limited per IP and per account.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and mint a new access token
         * @description Uses the refresh cookie. Presenting an already-used or revoked token is treated as theft and revokes the whole session family.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the session and clear cookies */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the caller's password
         * @description Verifies the current password, stores the new one, clears the forced first-login reset flag, and revokes every session; the client logs in again with the new credential.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts (admin) */
        get: operations["listUsers"];
        put?: never;
        /**
         * Provision a teacher or student (admin)
         * @description Creates the account with a generated one-time credential, returned exactly once in this response. The account must change its password on first login before any other endpoint works. Admin accounts are created only by the operator bootstrap, never over the API.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Deactivate, reset the credential, or edit an account (admin)
         * @description Disabling an account or resetting its credential revokes every live session immediately. Admins cannot disable or reset themselves here; that path goes through the auth endpoints. Each mutation writes an audit row in the same transaction.
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cohorts with member counts (admin) */
        get: operations["listGroups"];
        put?: never;
        /** Create a cohort (admin) */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a cohort's membership (admin)
         * @description Replaces the membership with exactly student_ids, validated and swapped in one transaction - a single bad id changes nothing. An empty list clears the cohort.
         */
        put: operations["setGroupMembers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's own quizzes (teacher)
         * @description Newest first, with question counts. Authoring is teacher-only.
         */
        get: operations["listQuizzes"];
        put?: never;
        /** Create a draft quiz (teacher) */
        post: operations["createQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * One quiz with its full question list (owner)
         * @description Owner-only; the questions include the answer keys. Non-owners get 404, never 403, so quiz existence is not leaked.
         */
        get: operations["getQuiz"];
        put?: never;
        post?: never;
        /**
         * Delete a draft quiz and its questions (owner)
         * @description Drafts only. Quizzes that ever left draft are never deleted - attempts may reference them; archiving is their retirement path.
         */
        delete: operations["deleteQuiz"];
        options?: never;
        head?: never;
        /**
         * Edit draft settings (owner)
         * @description Title, max_attempts, and shuffle_questions are editable while the quiz is a draft. Windows, duration, and guardrails are set at publish time.
         */
        patch: operations["updateQuiz"];
        trace?: never;
    };
    "/api/v1/quizzes/{id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a question to a draft quiz (owner)
         * @description Validated per type - a correct answer must exist among the options, points > 0, choice types need 2-8 options. The question is appended at the end of the running order.
         */
        post: operations["addQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{id}/questions/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder a draft quiz's questions (owner)
         * @description question_ids must list every question of the quiz exactly once; the API rewrites dense positions to match and returns the questions in the new order.
         */
        put: operations["reorderQuestions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a question from a draft quiz (owner)
         * @description Remaining positions are re-densified.
         */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        /**
         * Replace a question's content while its quiz is a draft (owner)
         * @description The full question content arrives every time (the editor autosaves whole-question state), so validation always sees a complete question.
         */
        patch: operations["updateQuestion"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
            commit: string;
            /** Format: date-time */
            time: string;
        };
        Ready: {
            status: string;
        };
        Error: {
            /** @description Stable machine-readable code from the docs/04-api.md vocabulary, e.g. INVALID_CREDENTIALS, UNAUTHENTICATED, VALIDATION_FAILED, RATE_LIMITED, PASSWORD_CHANGE_REQUIRED, NOT_FOUND. */
            code: string;
            message: string;
            /** @description Per-field messages for VALIDATION_FAILED. */
            fields?: {
                [key: string]: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "admin" | "teacher" | "student";
            /** Format: email */
            email: string;
            full_name: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** @description True while the account still uses its admin-issued credential; every endpoint except auth answers 403 PASSWORD_CHANGE_REQUIRED until the user sets their own password. */
            must_change_password: boolean;
            /** Format: date-time */
            created_at: string;
        };
        Session: {
            user: components["schemas"]["User"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        CreateUserRequest: {
            /** @enum {string} */
            role: "teacher" | "student";
            /** Format: email */
            email: string;
            full_name: string;
        };
        UpdateUserRequest: {
            full_name?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
            /** @description Issue a fresh one-time credential and revoke all sessions. */
            reset_password?: boolean;
        };
        ProvisionedUser: {
            user: components["schemas"]["User"];
            /** @description The generated one-time credential. Returned exactly once, never stored in the clear, never retrievable again. */
            initial_password?: string;
        };
        Quiz: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            title: string;
            /** @enum {string} */
            status: "draft" | "scheduled" | "live" | "closed" | "archived";
            /** Format: date-time */
            starts_at: string | null;
            /** Format: date-time */
            ends_at: string | null;
            duration_sec: number | null;
            max_attempts: number;
            shuffle_questions: boolean;
            /** Format: date-time */
            published_at: string | null;
            version: number;
            /** Format: date-time */
            created_at: string;
            question_count: number;
        };
        QuestionBody: {
            text: string;
            image_ref?: string;
        };
        QuestionOption: {
            key: string;
            text: string;
        };
        /** @description A question as any client may see it. The answer key is NOT part of this schema; only the owner-facing TeacherQuestion carries it, and the student serializer strips it structurally. */
        Question: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quiz_id: string;
            position: number;
            /** @enum {string} */
            type: "single" | "multi" | "truefalse" | "short";
            body: components["schemas"]["QuestionBody"];
            options?: components["schemas"]["QuestionOption"][];
            points: number;
            /** @enum {string} */
            source: "manual" | "import";
        };
        TeacherQuestion: components["schemas"]["Question"] & {
            /** @description The answer key. The option key (single), option keys (multi), a boolean (truefalse), or {accepted: [...]} (short). Owner-facing responses only. */
            correct: unknown;
        };
        QuestionInput: {
            /** @enum {string} */
            type: "single" | "multi" | "truefalse" | "short";
            body: components["schemas"]["QuestionBody"];
            /** @description Required for single/multi (2-8 entries); omitted otherwise. */
            options?: components["schemas"]["QuestionOption"][];
            /** @description The answer key; shape depends on type. Must reference existing option keys for choice types. */
            correct: unknown;
            /** @description Defaults to 1; must be positive. */
            points?: number;
        };
        UpdateQuizRequest: {
            title?: string;
            max_attempts?: number;
            shuffle_questions?: boolean;
        };
        QuizResponse: {
            quiz: components["schemas"]["Quiz"];
        };
        QuizDetail: {
            quiz: components["schemas"]["Quiz"];
            questions: components["schemas"]["TeacherQuestion"][];
        };
        QuestionResponse: {
            question: components["schemas"]["TeacherQuestion"];
        };
        Group: {
            /** Format: uuid */
            id: string;
            name: string;
            member_count: number;
            /** Format: date-time */
            created_at: string;
        };
        GroupResponse: {
            group: components["schemas"]["Group"];
        };
    };
    responses: {
        /** @description Missing, invalid, or expired credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Body-level validation failed; see fields. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The policy denies this action for the caller's role. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource. Also the answer for resources the caller is not assigned to, so existence is never leaked. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description QUIZ_NOT_EDITABLE - the quiz has been published; its question set is an immutable snapshot and drafts-only operations are refused. */
        NotEditable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many attempts; includes Retry-After. */
        RateLimited: {
            headers: {
                /** @description Seconds until the next attempt is allowed. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
            /** @description Not ready; keep traffic away. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session opened; cookies set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session rotated; new cookies set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. Always succeeds, even without a session. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; all sessions revoked, cookies cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                role?: "admin" | "teacher" | "student";
                status?: "active" | "disabled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users: components["schemas"]["User"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Account created; initial_password appears only here. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionedUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description The updated account; initial_password is present only when reset_password was requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionedUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cohorts, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        groups: components["schemas"]["Group"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Cohort created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    setGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    student_ids: string[];
                };
            };
        };
        responses: {
            /** @description Membership replaced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listQuizzes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's quizzes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        quizzes: components["schemas"]["Quiz"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                };
            };
        };
        responses: {
            /** @description Draft created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The quiz and its questions in position order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NotEditable"];
        };
    };
    updateQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuizRequest"];
            };
        };
        responses: {
            /** @description The updated quiz. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NotEditable"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    addQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionInput"];
            };
        };
        responses: {
            /** @description Question added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NotEditable"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    reorderQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question_ids: string[];
                };
            };
        };
        responses: {
            /** @description Questions in the new order with rewritten positions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        questions: components["schemas"]["TeacherQuestion"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NotEditable"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NotEditable"];
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionInput"];
            };
        };
        responses: {
            /** @description The updated question. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NotEditable"];
            422: components["responses"]["ValidationFailed"];
        };
    };
}
