// Package apischema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apischema

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AssignedQuizStatus.
const (
	AssignedQuizStatusClosed    AssignedQuizStatus = "closed"
	AssignedQuizStatusLive      AssignedQuizStatus = "live"
	AssignedQuizStatusScheduled AssignedQuizStatus = "scheduled"
)

// Defines values for AttemptStatus.
const (
	AttemptStatusGraded     AttemptStatus = "graded"
	AttemptStatusInProgress AttemptStatus = "in_progress"
	AttemptStatusKicked     AttemptStatus = "kicked"
	AttemptStatusSubmitted  AttemptStatus = "submitted"
)

// Defines values for AttemptSubmitKind.
const (
	AttemptSubmitKindAuto   AttemptSubmitKind = "auto"
	AttemptSubmitKindForced AttemptSubmitKind = "forced"
	AttemptSubmitKindKicked AttemptSubmitKind = "kicked"
	AttemptSubmitKindManual AttemptSubmitKind = "manual"
)

// Defines values for AttemptQuestionType.
const (
	AttemptQuestionTypeMulti     AttemptQuestionType = "multi"
	AttemptQuestionTypeShort     AttemptQuestionType = "short"
	AttemptQuestionTypeSingle    AttemptQuestionType = "single"
	AttemptQuestionTypeTruefalse AttemptQuestionType = "truefalse"
)

// Defines values for AttemptSummaryStatus.
const (
	AttemptSummaryStatusGraded     AttemptSummaryStatus = "graded"
	AttemptSummaryStatusInProgress AttemptSummaryStatus = "in_progress"
	AttemptSummaryStatusKicked     AttemptSummaryStatus = "kicked"
	AttemptSummaryStatusSubmitted  AttemptSummaryStatus = "submitted"
)

// Defines values for CreateUserRequestRole.
const (
	CreateUserRequestRoleStudent CreateUserRequestRole = "student"
	CreateUserRequestRoleTeacher CreateUserRequestRole = "teacher"
)

// Defines values for GuardrailsFocusTracking.
const (
	GuardrailsFocusTrackingCount GuardrailsFocusTracking = "count"
	GuardrailsFocusTrackingOff   GuardrailsFocusTracking = "off"
	GuardrailsFocusTrackingWarn  GuardrailsFocusTracking = "warn"
)

// Defines values for GuardrailsFullscreen.
const (
	GuardrailsFullscreenCount GuardrailsFullscreen = "count"
	GuardrailsFullscreenOff   GuardrailsFullscreen = "off"
	GuardrailsFullscreenWarn  GuardrailsFullscreen = "warn"
)

// Defines values for GuardrailsViolationAction.
const (
	AutoSubmit GuardrailsViolationAction = "auto_submit"
	Flag       GuardrailsViolationAction = "flag"
	Notify     GuardrailsViolationAction = "notify"
)

// Defines values for HealthStatus.
const (
	HealthStatusError HealthStatus = "error"
	HealthStatusOk    HealthStatus = "ok"
)

// Defines values for ImportStatus.
const (
	ImportStatusCommitted  ImportStatus = "committed"
	ImportStatusFailed     ImportStatus = "failed"
	ImportStatusReady      ImportStatus = "ready"
	ImportStatusValidating ImportStatus = "validating"
)

// Defines values for LiveRosterRowState.
const (
	LiveRosterRowStateDisconnected LiveRosterRowState = "disconnected"
	LiveRosterRowStateInProgress   LiveRosterRowState = "in_progress"
	LiveRosterRowStateKicked       LiveRosterRowState = "kicked"
	LiveRosterRowStateNotStarted   LiveRosterRowState = "not_started"
	LiveRosterRowStateSubmitted    LiveRosterRowState = "submitted"
)

// Defines values for LiveRosterRowStatus.
const (
	LiveRosterRowStatusGraded     LiveRosterRowStatus = "graded"
	LiveRosterRowStatusInProgress LiveRosterRowStatus = "in_progress"
	LiveRosterRowStatusKicked     LiveRosterRowStatus = "kicked"
	LiveRosterRowStatusSubmitted  LiveRosterRowStatus = "submitted"
)

// Defines values for LiveRosterRowSubmitKind.
const (
	LiveRosterRowSubmitKindAuto   LiveRosterRowSubmitKind = "auto"
	LiveRosterRowSubmitKindForced LiveRosterRowSubmitKind = "forced"
	LiveRosterRowSubmitKindKicked LiveRosterRowSubmitKind = "kicked"
	LiveRosterRowSubmitKindManual LiveRosterRowSubmitKind = "manual"
)

// Defines values for PublishQuizRequestReleasePolicy.
const (
	PublishQuizRequestReleasePolicyAuto   PublishQuizRequestReleasePolicy = "auto"
	PublishQuizRequestReleasePolicyManual PublishQuizRequestReleasePolicy = "manual"
)

// Defines values for QuestionSource.
const (
	QuestionSourceImport QuestionSource = "import"
	QuestionSourceManual QuestionSource = "manual"
)

// Defines values for QuestionType.
const (
	QuestionTypeMulti     QuestionType = "multi"
	QuestionTypeShort     QuestionType = "short"
	QuestionTypeSingle    QuestionType = "single"
	QuestionTypeTruefalse QuestionType = "truefalse"
)

// Defines values for QuestionInputType.
const (
	QuestionInputTypeMulti     QuestionInputType = "multi"
	QuestionInputTypeShort     QuestionInputType = "short"
	QuestionInputTypeSingle    QuestionInputType = "single"
	QuestionInputTypeTruefalse QuestionInputType = "truefalse"
)

// Defines values for QuizReleasePolicy.
const (
	QuizReleasePolicyAuto   QuizReleasePolicy = "auto"
	QuizReleasePolicyManual QuizReleasePolicy = "manual"
)

// Defines values for QuizStatus.
const (
	QuizStatusArchived  QuizStatus = "archived"
	QuizStatusClosed    QuizStatus = "closed"
	QuizStatusDraft     QuizStatus = "draft"
	QuizStatusLive      QuizStatus = "live"
	QuizStatusScheduled QuizStatus = "scheduled"
)

// Defines values for ResultQuestionType.
const (
	ResultQuestionTypeMulti     ResultQuestionType = "multi"
	ResultQuestionTypeShort     ResultQuestionType = "short"
	ResultQuestionTypeSingle    ResultQuestionType = "single"
	ResultQuestionTypeTruefalse ResultQuestionType = "truefalse"
)

// Defines values for ResultRowStatus.
const (
	Graded     ResultRowStatus = "graded"
	InProgress ResultRowStatus = "in_progress"
	Kicked     ResultRowStatus = "kicked"
	Submitted  ResultRowStatus = "submitted"
)

// Defines values for ResultRowSubmitKind.
const (
	ResultRowSubmitKindAuto   ResultRowSubmitKind = "auto"
	ResultRowSubmitKindForced ResultRowSubmitKind = "forced"
	ResultRowSubmitKindKicked ResultRowSubmitKind = "kicked"
	ResultRowSubmitKindManual ResultRowSubmitKind = "manual"
)

// Defines values for StudentOverviewStatus.
const (
	StudentOverviewStatusActive   StudentOverviewStatus = "active"
	StudentOverviewStatusDisabled StudentOverviewStatus = "disabled"
)

// Defines values for TeacherOverviewStatus.
const (
	TeacherOverviewStatusActive   TeacherOverviewStatus = "active"
	TeacherOverviewStatusDisabled TeacherOverviewStatus = "disabled"
)

// Defines values for TeacherQuestionSource.
const (
	TeacherQuestionSourceImport TeacherQuestionSource = "import"
	TeacherQuestionSourceManual TeacherQuestionSource = "manual"
)

// Defines values for TeacherQuestionType.
const (
	Multi     TeacherQuestionType = "multi"
	Short     TeacherQuestionType = "short"
	Single    TeacherQuestionType = "single"
	Truefalse TeacherQuestionType = "truefalse"
)

// Defines values for TeacherStudentPerformanceQuizzesStatus.
const (
	Archived  TeacherStudentPerformanceQuizzesStatus = "archived"
	Closed    TeacherStudentPerformanceQuizzesStatus = "closed"
	Draft     TeacherStudentPerformanceQuizzesStatus = "draft"
	Live      TeacherStudentPerformanceQuizzesStatus = "live"
	Scheduled TeacherStudentPerformanceQuizzesStatus = "scheduled"
)

// Defines values for UpdateUserRequestStatus.
const (
	UpdateUserRequestStatusActive   UpdateUserRequestStatus = "active"
	UpdateUserRequestStatusDisabled UpdateUserRequestStatus = "disabled"
)

// Defines values for UserRole.
const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleStudent UserRole = "student"
	UserRoleTeacher UserRole = "teacher"
)

// Defines values for UserStatus.
const (
	UserStatusActive   UserStatus = "active"
	UserStatusDisabled UserStatus = "disabled"
)

// Defines values for ViolationTallyType.
const (
	ViolationTallyTypeClipboard  ViolationTallyType = "clipboard"
	ViolationTallyTypeFocus      ViolationTallyType = "focus"
	ViolationTallyTypeFullscreen ViolationTallyType = "fullscreen"
)

// Defines values for ReportAttemptViolationJSONBodyType.
const (
	ReportAttemptViolationJSONBodyTypeClipboard  ReportAttemptViolationJSONBodyType = "clipboard"
	ReportAttemptViolationJSONBodyTypeFocus      ReportAttemptViolationJSONBodyType = "focus"
	ReportAttemptViolationJSONBodyTypeFullscreen ReportAttemptViolationJSONBodyType = "fullscreen"
)

// Defines values for ListUsersParamsRole.
const (
	Admin   ListUsersParamsRole = "admin"
	Student ListUsersParamsRole = "student"
	Teacher ListUsersParamsRole = "teacher"
)

// Defines values for ListUsersParamsStatus.
const (
	Active   ListUsersParamsStatus = "active"
	Disabled ListUsersParamsStatus = "disabled"
)

// AssignedQuiz The student-facing quiz shape - window, budget, size, and the caller's own attempt history. Never the owner, the guardrail internals, or (structurally) a question.
type AssignedQuiz struct {
	// Attempts The caller's own attempts, oldest first.
	Attempts      []AttemptSummary   `json:"attempts"`
	DurationSec   int                `json:"duration_sec"`
	EndsAt        time.Time          `json:"ends_at"`
	Id            openapi_types.UUID `json:"id"`
	MaxAttempts   int                `json:"max_attempts"`
	QuestionCount int                `json:"question_count"`

	// ResultsReleasedAt Null means scores are withheld.
	ResultsReleasedAt *time.Time `json:"results_released_at"`
	StartsAt          time.Time  `json:"starts_at"`

	// Status Derived from the window on read.
	Status  AssignedQuizStatus `json:"status"`
	Title   string             `json:"title"`
	Version int                `json:"version"`
}

// AssignedQuizStatus Derived from the window on read.
type AssignedQuizStatus string

// AssignedStudent defines model for AssignedStudent.
type AssignedStudent struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"full_name"`
	Id       openapi_types.UUID  `json:"id"`
}

// AssignmentsResponse defines model for AssignmentsResponse.
type AssignmentsResponse struct {
	Students []AssignedStudent `json:"students"`
}

// Attempt The student-facing attempt shape. The owner is always the caller and the score is withheld until the results-release policy lands with grading, so neither appears here.
type Attempt struct {
	AttemptNo int `json:"attempt_no"`

	// DeadlineAt least(started_at + duration, quiz.ends_at); precomputed once at start, the single column every write validates against.
	DeadlineAt time.Time          `json:"deadline_at"`
	Id         openapi_types.UUID `json:"id"`
	QuizId     openapi_types.UUID `json:"quiz_id"`

	// QuizVersion Pins the snapshot the student saw.
	QuizVersion    int                `json:"quiz_version"`
	StartedAt      time.Time          `json:"started_at"`
	Status         AttemptStatus      `json:"status"`
	SubmitKind     *AttemptSubmitKind `json:"submit_kind"`
	SubmittedAt    *time.Time         `json:"submitted_at"`
	ViolationCount int                `json:"violation_count"`
}

// AttemptStatus defines model for Attempt.Status.
type AttemptStatus string

// AttemptSubmitKind defines model for Attempt.SubmitKind.
type AttemptSubmitKind string

// AttemptAnswer defines model for AttemptAnswer.
type AttemptAnswer struct {
	QuestionId openapi_types.UUID `json:"question_id"`

	// Response The autosaved response; shape depends on question type - the option key (single), option keys (multi), a boolean (truefalse), or a string (short).
	Response    interface{} `json:"response"`
	SavedAt     time.Time   `json:"saved_at"`
	TimeSpentMs int         `json:"time_spent_ms"`
}

// AttemptDetail The full player payload - attempt, quiz identity, snapshotted guardrails, questions without the answer key, saved answers, and the server clock for the cosmetic countdown.
type AttemptDetail struct {
	Answers []AttemptAnswer `json:"answers"`

	// Attempt The student-facing attempt shape. The owner is always the caller and the score is withheld until the results-release policy lands with grading, so neither appears here.
	Attempt Attempt `json:"attempt"`

	// Guardrails Per-quiz anti-cheat config, snapshotted with the question set at publish so rules cannot change under a student mid-window.
	Guardrails Guardrails `json:"guardrails"`

	// Now Current server time, for the clock-offset estimate.
	Now       time.Time         `json:"now"`
	Questions []AttemptQuestion `json:"questions"`
	QuizTitle string            `json:"quiz_title"`
}

// AttemptQuestion One snapshot question as the player sees it. The answer key is structurally absent; when the quiz shuffles, positions are renumbered densely in the per-attempt order.
type AttemptQuestion struct {
	Body     QuestionBody        `json:"body"`
	Id       openapi_types.UUID  `json:"id"`
	Options  *[]QuestionOption   `json:"options,omitempty"`
	Points   float32             `json:"points"`
	Position int                 `json:"position"`
	Type     AttemptQuestionType `json:"type"`
}

// AttemptQuestionType defines model for AttemptQuestion.Type.
type AttemptQuestionType string

// AttemptResponse defines model for AttemptResponse.
type AttemptResponse struct {
	// Attempt The student-facing attempt shape. The owner is always the caller and the score is withheld until the results-release policy lands with grading, so neither appears here.
	Attempt Attempt `json:"attempt"`
}

// AttemptResult The released results payload for one attempt. The attempt keeps its usual score-free shape; the released score rides at the top level.
type AttemptResult struct {
	// Attempt The student-facing attempt shape. The owner is always the caller and the score is withheld until the results-release policy lands with grading, so neither appears here.
	Attempt  Attempt `json:"attempt"`
	MaxScore float32 `json:"max_score"`

	// Percentile This attempt's score, ranked against the quiz's score distribution (docs/07 section 3, "score and percentile per quiz"). Bucket-granular (derived from the 10-bucket quiz_stats histogram, not an exact rank) and null when no points are possible on the quiz or the quiz_stats rollup hasn't landed yet.
	Percentile *float32         `json:"percentile"`
	Questions  []ResultQuestion `json:"questions"`
	QuizTitle  string           `json:"quiz_title"`
	ReleasedAt time.Time        `json:"released_at"`
	Score      float32          `json:"score"`

	// ScoreOverridden True once the teacher has overridden this attempt's score to zero (docs/06 line 80) - only ever true for a kicked attempt.
	ScoreOverridden bool `json:"score_overridden"`
}

// AttemptSummary One of the caller's own attempts as the assigned list shows it. score stays null until the quiz's results are released.
type AttemptSummary struct {
	AttemptNo   int                  `json:"attempt_no"`
	Id          openapi_types.UUID   `json:"id"`
	Score       *float32             `json:"score"`
	StartedAt   time.Time            `json:"started_at"`
	Status      AttemptSummaryStatus `json:"status"`
	SubmittedAt *time.Time           `json:"submitted_at"`
}

// AttemptSummaryStatus defines model for AttemptSummary.Status.
type AttemptSummaryStatus string

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	// Action The action verb, e.g. quizzes.published, attempt.kicked.
	Action string `json:"action"`

	// ActorId The account that performed the action; omitted when the column is null (system action).
	ActorId *openapi_types.UUID `json:"actor_id,omitempty"`
	At      time.Time           `json:"at"`

	// Detail Free-form JSON detail (includes the diff for mutations); null when the writer recorded none.
	Detail *interface{} `json:"detail"`

	// Id The bigserial primary key; also the pagination cursor.
	Id int64 `json:"id"`

	// ResourceId Omitted when the column is null.
	ResourceId   *openapi_types.UUID `json:"resource_id,omitempty"`
	ResourceType string              `json:"resource_type"`
}

// AuditPage defines model for AuditPage.
type AuditPage struct {
	Entries []AuditEntry `json:"entries"`

	// NextCursor Pass as `before` to fetch the next page; null on the last page.
	NextCursor *int64 `json:"next_cursor"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// CohortStats One group's members compared against the platform-wide student-analytics profile.
type CohortStats struct {
	AvgAccuracy       *float32           `json:"avg_accuracy"`
	AvgCompletionRate *float32           `json:"avg_completion_rate"`
	GroupId           openapi_types.UUID `json:"group_id"`
	GroupName         string             `json:"group_name"`
	MemberCount       int                `json:"member_count"`
}

// CommitImportResponse docs/07 section 2 step 5: the import, now status "committed", plus the questions it inserted (tagged source "import" with import_id for provenance).
type CommitImportResponse struct {
	// Import A registered bulk upload (docs/07 section 2). status moves validating -> ready|failed -> committed; row_count and error_report are null until the worker's validation pass resolves it.
	Import    Import            `json:"import"`
	Questions []TeacherQuestion `json:"questions"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email    openapi_types.Email   `json:"email"`
	FullName string                `json:"full_name"`
	Role     CreateUserRequestRole `json:"role"`
}

// CreateUserRequestRole defines model for CreateUserRequest.Role.
type CreateUserRequestRole string

// DeployCheck defines model for DeployCheck.
type DeployCheck struct {
	LiveQuizCount int     `json:"live_quiz_count"`
	Reason        *string `json:"reason,omitempty"`
	SafeToDeploy  bool    `json:"safe_to_deploy"`
}

// DirectoryResponse The audience picker's world - active students plus cohorts. Students share the AssignedStudent shape, so the picker and the assigned audience list render from one type.
type DirectoryResponse struct {
	Groups   []Group           `json:"groups"`
	Students []AssignedStudent `json:"students"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable code from the docs/04-api.md vocabulary, e.g. INVALID_CREDENTIALS, UNAUTHENTICATED, VALIDATION_FAILED, RATE_LIMITED, PASSWORD_CHANGE_REQUIRED, NOT_FOUND.
	Code string `json:"code"`

	// Fields Per-field messages for VALIDATION_FAILED.
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt   time.Time          `json:"created_at"`
	Id          openapi_types.UUID `json:"id"`
	MemberCount int                `json:"member_count"`
	Name        string             `json:"name"`
}

// GroupResponse defines model for GroupResponse.
type GroupResponse struct {
	Group Group `json:"group"`
}

// Guardrails Per-quiz anti-cheat config, snapshotted with the question set at publish so rules cannot change under a student mid-window.
type Guardrails struct {
	BlockClipboard  bool                      `json:"block_clipboard"`
	FocusTracking   GuardrailsFocusTracking   `json:"focus_tracking"`
	Fullscreen      GuardrailsFullscreen      `json:"fullscreen"`
	MaxViolations   int                       `json:"max_violations"`
	ViolationAction GuardrailsViolationAction `json:"violation_action"`
}

// GuardrailsFocusTracking defines model for Guardrails.FocusTracking.
type GuardrailsFocusTracking string

// GuardrailsFullscreen defines model for Guardrails.Fullscreen.
type GuardrailsFullscreen string

// GuardrailsViolationAction defines model for Guardrails.ViolationAction.
type GuardrailsViolationAction string

// Health defines model for Health.
type Health struct {
	Checks struct {
		Database        *string  `json:"database,omitempty"`
		QueueLagSeconds *float32 `json:"queue_lag_seconds,omitempty"`
		Redis           *string  `json:"redis,omitempty"`
	} `json:"checks"`
	Commit  string       `json:"commit"`
	Status  HealthStatus `json:"status"`
	Time    time.Time    `json:"time"`
	Version string       `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Import A registered bulk upload (docs/07 section 2). status moves validating -> ready|failed -> committed; row_count and error_report are null until the worker's validation pass resolves it.
type Import struct {
	CreatedAt   time.Time `json:"created_at"`
	ErrorReport *[]struct {
		Column  string `json:"column"`
		Message string `json:"message"`
		Row     int    `json:"row"`
	} `json:"error_report"`
	Id         openapi_types.UUID `json:"id"`
	QuizId     openapi_types.UUID `json:"quiz_id"`
	RowCount   *int               `json:"row_count"`
	Status     ImportStatus       `json:"status"`
	UploadedBy openapi_types.UUID `json:"uploaded_by"`
}

// ImportStatus defines model for Import.Status.
type ImportStatus string

// ImportResponse defines model for ImportResponse.
type ImportResponse struct {
	// Import A registered bulk upload (docs/07 section 2). status moves validating -> ready|failed -> committed; row_count and error_report are null until the worker's validation pass resolves it.
	Import Import `json:"import"`
}

// IntegrityStudent defines model for IntegrityStudent.
type IntegrityStudent struct {
	Kicked     bool               `json:"kicked"`
	StudentId  openapi_types.UUID `json:"student_id"`
	Violations int                `json:"violations"`
}

// IntegritySummary defines model for IntegritySummary.
type IntegritySummary struct {
	FlaggedStudents int                `json:"flagged_students"`
	KickedAttempts  int                `json:"kicked_attempts"`
	PerStudent      []IntegrityStudent `json:"per_student"`
	TotalViolations int                `json:"total_violations"`
}

// ItemStat One question's row in item_analysis, over each student's best graded attempt.
type ItemStat struct {
	AvgTimeMs       float32        `json:"avg_time_ms"`
	OptionPickRates map[string]int `json:"option_pick_rates"`

	// PValue Fraction of responses that were correct (difficulty).
	PValue float32 `json:"p_value"`

	// PointBiserial Item-discrimination correlation; null when undefined.
	PointBiserial *float32           `json:"point_biserial"`
	QuestionId    openapi_types.UUID `json:"question_id"`
	Responses     int                `json:"responses"`
}

// Leaderboard A quiz's ranked standings as seen by one student: the leading entries plus, always, the reader's own row even when it falls outside them.
type Leaderboard struct {
	Entries   []LeaderboardEntry `json:"entries"`
	QuizTitle string             `json:"quiz_title"`

	// Total How many students are ranked in all - the "of 48" beside a rank - which may exceed the length of `entries`.
	Total int `json:"total"`
}

// LeaderboardEntry One student's standing on a quiz, from their best graded attempt.
type LeaderboardEntry struct {
	// Accuracy Share of the pinned snapshot's points earned, 0..1. Null when the snapshot the student saw carries no points at all; such students rank last.
	Accuracy *float32 `json:"accuracy"`
	FullName string   `json:"full_name"`

	// IsSelf True on the reading student's own row.
	IsSelf bool `json:"is_self"`

	// Rank Competition rank (1-based). Students whose accuracy and time taken both tie share a rank, and the next rank skips accordingly.
	Rank      int                `json:"rank"`
	StudentId openapi_types.UUID `json:"student_id"`
}

// LiveRosterResponse defines model for LiveRosterResponse.
type LiveRosterResponse struct {
	Quiz   Quiz            `json:"quiz"`
	Roster []LiveRosterRow `json:"roster"`

	// ServerTime The database clock the row timestamps were read against.
	ServerTime time.Time `json:"server_time"`
}

// LiveRosterRow One roster cell - an assigned student and their latest attempt. Students who never started read as not_started with the attempt fields null. state collapses the attempt status to the dashboard vocabulary; graded folds into submitted. disconnected is in_progress plus a stale heartbeat (docs/05 section 5) - the deadline clock keeps running.
type LiveRosterRow struct {
	// AnsweredCount Questions with a non-null saved response.
	AnsweredCount *int                `json:"answered_count"`
	AttemptId     *openapi_types.UUID `json:"attempt_id"`
	AttemptNo     *int                `json:"attempt_no"`

	// CurrentQuestion 1-based ordinal (within the pinned quiz_version's questions array) of the last question the student saved an answer for. Null until the first autosave.
	CurrentQuestion *int                `json:"current_question"`
	DeadlineAt      *time.Time          `json:"deadline_at"`
	Email           openapi_types.Email `json:"email"`
	FullName        string              `json:"full_name"`

	// MaxScore Total points of the snapshot version this attempt pinned.
	MaxScore *float32 `json:"max_score"`

	// QuestionCount Question count of the snapshot version this attempt pinned.
	QuestionCount  *int                     `json:"question_count"`
	Score          *float32                 `json:"score"`
	StartedAt      *time.Time               `json:"started_at"`
	State          LiveRosterRowState       `json:"state"`
	Status         *LiveRosterRowStatus     `json:"status"`
	StudentId      openapi_types.UUID       `json:"student_id"`
	SubmitKind     *LiveRosterRowSubmitKind `json:"submit_kind"`
	ViolationCount *int                     `json:"violation_count"`

	// Violations Per-type tally of every attempt.violation logged for this attempt - the evidence behind the roster badge's "types on hover" (docs/05 section 2, docs/06 section 3). Empty for a student who never started. Its counts sum to at least violation_count and often to more: violation_count is the ladder tally, which advances only for a guardrail whose snapshotted policy is "count", while warn-policy and clipboard reports are logged here without counting.
	Violations []ViolationTally `json:"violations"`
}

// LiveRosterRowState defines model for LiveRosterRow.State.
type LiveRosterRowState string

// LiveRosterRowStatus defines model for LiveRosterRow.Status.
type LiveRosterRowStatus string

// LiveRosterRowSubmitKind defines model for LiveRosterRow.SubmitKind.
type LiveRosterRowSubmitKind string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// OrgStats The admin org-wide dashboard (docs/07 section 4, FR-9). Every field is computed live: there is no org_stats rollup table.
type OrgStats struct {
	ActiveUsers struct {
		Admins   int `json:"admins"`
		Students int `json:"students"`
		Teachers int `json:"teachers"`
	} `json:"active_users"`
	CohortComparisons []CohortStats `json:"cohort_comparisons"`

	// PlatformParticipation Mean participation across every rolled-up quiz_stats row.
	PlatformParticipation *float32 `json:"platform_participation"`

	// QuizzesPerWeek Quizzes created per week over the trailing 12 weeks, oldest first. A week with no quizzes created is simply absent.
	QuizzesPerWeek []struct {
		Count     int       `json:"count"`
		WeekStart time.Time `json:"week_start"`
	} `json:"quizzes_per_week"`
}

// ProvisionedUser defines model for ProvisionedUser.
type ProvisionedUser struct {
	// InitialPassword The generated one-time credential. Returned exactly once, never stored in the clear, never retrievable again.
	InitialPassword *string `json:"initial_password,omitempty"`
	User            User    `json:"user"`
}

// PublishQuizRequest defines model for PublishQuizRequest.
type PublishQuizRequest struct {
	// DurationSec Per-attempt time budget; a student starting late gets min(duration, time-to-close).
	DurationSec int `json:"duration_sec"`

	// EndsAt Hard close; must be after starts_at.
	EndsAt time.Time `json:"ends_at"`

	// Guardrails Per-quiz anti-cheat config, snapshotted with the question set at publish so rules cannot change under a student mid-window.
	Guardrails *Guardrails `json:"guardrails,omitempty"`

	// ReleasePolicy When scores become visible to students - auto (the default when omitted) releases at close once grading lands, manual waits for the teacher's explicit release.
	ReleasePolicy *PublishQuizRequestReleasePolicy `json:"release_policy,omitempty"`

	// StartsAt Go-live moment; must be in the future.
	StartsAt time.Time `json:"starts_at"`
}

// PublishQuizRequestReleasePolicy When scores become visible to students - auto (the default when omitted) releases at close once grading lands, manual waits for the teacher's explicit release.
type PublishQuizRequestReleasePolicy string

// Question A question as any client may see it. The answer key is NOT part of this schema; only the owner-facing TeacherQuestion carries it, and the student serializer strips it structurally.
type Question struct {
	Body     QuestionBody       `json:"body"`
	Id       openapi_types.UUID `json:"id"`
	Options  *[]QuestionOption  `json:"options,omitempty"`
	Points   float32            `json:"points"`
	Position int                `json:"position"`
	QuizId   openapi_types.UUID `json:"quiz_id"`
	Source   QuestionSource     `json:"source"`

	// Topic Free-text topic tag, or null when the question is untagged. Tags are frozen into the version snapshot on publish and drive StudentStats.topic_strengths.
	Topic *string      `json:"topic"`
	Type  QuestionType `json:"type"`
}

// QuestionSource defines model for Question.Source.
type QuestionSource string

// QuestionType defines model for Question.Type.
type QuestionType string

// QuestionBody defines model for QuestionBody.
type QuestionBody struct {
	ImageRef *string `json:"image_ref,omitempty"`
	Text     string  `json:"text"`
}

// QuestionInput defines model for QuestionInput.
type QuestionInput struct {
	Body QuestionBody `json:"body"`

	// Correct The answer key; shape depends on type. Must reference existing option keys for choice types.
	Correct interface{} `json:"correct"`

	// Options Required for single/multi (2-8 entries); omitted otherwise.
	Options *[]QuestionOption `json:"options,omitempty"`

	// Points Defaults to 1; must be positive.
	Points *float32 `json:"points,omitempty"`

	// Topic Optional free-text topic tag, 1-60 characters after trimming. Omitted, null, or blank leaves the question untagged.
	Topic *string           `json:"topic"`
	Type  QuestionInputType `json:"type"`
}

// QuestionInputType defines model for QuestionInput.Type.
type QuestionInputType string

// QuestionOption defines model for QuestionOption.
type QuestionOption struct {
	Key  string `json:"key"`
	Text string `json:"text"`
}

// QuestionResponse defines model for QuestionResponse.
type QuestionResponse struct {
	Question TeacherQuestion `json:"question"`
}

// Quiz defines model for Quiz.
type Quiz struct {
	CreatedAt   time.Time  `json:"created_at"`
	DurationSec *int       `json:"duration_sec"`
	EndsAt      *time.Time `json:"ends_at"`

	// Guardrails The anti-cheat ladder frozen at publish. Null while the quiz is a draft (never published); populated from the publish request once scheduled, so reopening a scheduled quiz reseeds its real settings.
	Guardrails    *Guardrails        `json:"guardrails"`
	Id            openapi_types.UUID `json:"id"`
	MaxAttempts   int                `json:"max_attempts"`
	OwnerId       openapi_types.UUID `json:"owner_id"`
	PublishedAt   *time.Time         `json:"published_at"`
	QuestionCount int                `json:"question_count"`

	// ReleasePolicy When scores become visible to students - auto releases in the worker pass that grades the closed quiz, manual waits for POST /quizzes/{id}/release-results.
	ReleasePolicy QuizReleasePolicy `json:"release_policy"`

	// ResultsReleasedAt Null means scores and the answer key are withheld.
	ResultsReleasedAt *time.Time `json:"results_released_at"`
	ShuffleQuestions  bool       `json:"shuffle_questions"`
	StartsAt          *time.Time `json:"starts_at"`
	Status            QuizStatus `json:"status"`
	Title             string     `json:"title"`
	Version           int        `json:"version"`
}

// QuizReleasePolicy When scores become visible to students - auto releases in the worker pass that grades the closed quiz, manual waits for POST /quizzes/{id}/release-results.
type QuizReleasePolicy string

// QuizStatus defines model for Quiz.Status.
type QuizStatus string

// QuizDetail defines model for QuizDetail.
type QuizDetail struct {
	Questions []TeacherQuestion `json:"questions"`
	Quiz      Quiz              `json:"quiz"`
}

// QuizResponse defines model for QuizResponse.
type QuizResponse struct {
	Quiz Quiz `json:"quiz"`
}

// QuizResultsResponse defines model for QuizResultsResponse.
type QuizResultsResponse struct {
	Quiz    Quiz        `json:"quiz"`
	Results []ResultRow `json:"results"`
}

// QuizStats The quiz_stats row for the wire (docs/03-data-model.md). Frozen at close by RollupDue; a dashboard read is one primary-key lookup, never a live recompute.
type QuizStats struct {
	ComputedAt time.Time `json:"computed_at"`

	// Distribution 10 equal-width percentage-of-max-score buckets (0-10%, 10-20%, ..., 90-100%), each the count of best-attempt scores falling in it.
	Distribution []int            `json:"distribution"`
	Integrity    IntegritySummary `json:"integrity"`
	ItemAnalysis []ItemStat       `json:"item_analysis"`
	Mean         *float32         `json:"mean"`
	Median       *float32         `json:"median"`

	// Participation Fraction of assigned students with a graded attempt.
	Participation *float32           `json:"participation"`
	QuizId        openapi_types.UUID `json:"quiz_id"`
}

// Ready defines model for Ready.
type Ready struct {
	Status string `json:"status"`
}

// ResultQuestion One snapshot question in the released review - what was asked, what the student answered, the key, and what it earned. Unanswered questions keep response and is_correct null.
type ResultQuestion struct {
	Body QuestionBody `json:"body"`

	// Correct The answer key - exposed here only, after close and release (the documented exception to answer-key isolation).
	Correct       interface{}        `json:"correct"`
	Id            openapi_types.UUID `json:"id"`
	IsCorrect     *bool              `json:"is_correct"`
	Options       *[]QuestionOption  `json:"options,omitempty"`
	Points        float32            `json:"points"`
	PointsAwarded float32            `json:"points_awarded"`
	Position      int                `json:"position"`

	// Response The autosaved response; shape depends on question type.
	Response *interface{}       `json:"response"`
	Type     ResultQuestionType `json:"type"`
}

// ResultQuestionType defines model for ResultQuestion.Type.
type ResultQuestionType string

// ResultRow One line of the teacher's results table - an assigned student and one of their attempts. Students who never started keep the attempt fields null.
type ResultRow struct {
	AttemptId *openapi_types.UUID `json:"attempt_id"`
	AttemptNo *int                `json:"attempt_no"`
	Email     openapi_types.Email `json:"email"`
	FullName  string              `json:"full_name"`

	// MaxScore Total points of the snapshot version this attempt pinned.
	MaxScore *float32 `json:"max_score"`
	Score    *float32 `json:"score"`

	// ScoreOverridden True once the teacher has overridden this attempt's score to zero (docs/06 line 80, POST /attempts/:id/override-score) - only ever true for a kicked attempt.
	ScoreOverridden bool                 `json:"score_overridden"`
	StartedAt       *time.Time           `json:"started_at"`
	Status          *ResultRowStatus     `json:"status"`
	StudentId       openapi_types.UUID   `json:"student_id"`
	SubmitKind      *ResultRowSubmitKind `json:"submit_kind"`
	SubmittedAt     *time.Time           `json:"submitted_at"`
}

// ResultRowStatus defines model for ResultRow.Status.
type ResultRowStatus string

// ResultRowSubmitKind defines model for ResultRow.SubmitKind.
type ResultRowSubmitKind string

// SaveAnswerRequest defines model for SaveAnswerRequest.
type SaveAnswerRequest struct {
	// Response The response value; shape depends on question type.
	Response interface{} `json:"response"`

	// TimeSpentMs Accumulated focus time on this question, for analytics.
	TimeSpentMs *int `json:"time_spent_ms,omitempty"`
}

// SaveAnswerResponse defines model for SaveAnswerResponse.
type SaveAnswerResponse struct {
	Answer     AttemptAnswer `json:"answer"`
	DeadlineAt time.Time     `json:"deadline_at"`
	Now        time.Time     `json:"now"`
}

// Session defines model for Session.
type Session struct {
	User User `json:"user"`
}

// SetAssignmentsRequest defines model for SetAssignmentsRequest.
type SetAssignmentsRequest struct {
	// GroupIds Expanded to individual student rows at assignment time.
	GroupIds   *[]openapi_types.UUID `json:"group_ids,omitempty"`
	StudentIds *[]openapi_types.UUID `json:"student_ids,omitempty"`
}

// StudentOverview One admin-analytics row per student - identity, cohort memberships, and a summary of the student_stats rollup. Averages are null until the student's first terminal quiz rolls up.
type StudentOverview struct {
	// AvgAccuracy Mean best-attempt accuracy across terminal quizzes, 0-1.
	AvgAccuracy        *float32             `json:"avg_accuracy"`
	AvgTimePerQuestion *float32             `json:"avg_time_per_question"`
	CompletionRate     *float32             `json:"completion_rate"`
	Email              string               `json:"email"`
	FullName           string               `json:"full_name"`
	GroupIds           []openapi_types.UUID `json:"group_ids"`

	// QuizzesTaken Terminal quizzes in the student's accuracy trend.
	QuizzesTaken int                   `json:"quizzes_taken"`
	Status       StudentOverviewStatus `json:"status"`
	StudentId    openapi_types.UUID    `json:"student_id"`
	UpdatedAt    *time.Time            `json:"updated_at"`
}

// StudentOverviewStatus defines model for StudentOverview.Status.
type StudentOverviewStatus string

// StudentStats The student_stats row for the wire (docs/03-data-model.md).
type StudentStats struct {
	// AccuracyTrend The student's best-attempt accuracy per terminal quiz, submission-ordered.
	AccuracyTrend []struct {
		Accuracy    *float32           `json:"accuracy"`
		QuizId      openapi_types.UUID `json:"quiz_id"`
		SubmittedAt time.Time          `json:"submitted_at"`
	} `json:"accuracy_trend"`
	AvgTimePerQuestion *float32           `json:"avg_time_per_question"`
	CompletionRate     *float32           `json:"completion_rate"`
	StudentId          openapi_types.UUID `json:"student_id"`

	// TopicStrengths Accuracy per question topic tag, 0-1, over the student's best graded attempt on each terminal quiz. Only answered questions of a tagged topic count, mirroring item analysis' p-value denominator. Empty when none of the student's questions carried a topic tag.
	TopicStrengths map[string]float32 `json:"topic_strengths"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

// TeacherOverview One admin-analytics row per teacher - identity plus the TeacherStats aggregates, computed live in one query across all teachers.
type TeacherOverview struct {
	// AvgClassScore Mean of each rolled-up quiz's mean, in raw points (see TeacherStats).
	AvgClassScore    *float32              `json:"avg_class_score"`
	AvgParticipation *float32              `json:"avg_participation"`
	Email            string                `json:"email"`
	FullName         string                `json:"full_name"`
	QuizzesConducted int                   `json:"quizzes_conducted"`
	QuizzesCreated   int                   `json:"quizzes_created"`
	Status           TeacherOverviewStatus `json:"status"`
	TeacherId        openapi_types.UUID    `json:"teacher_id"`
	TotalAttempts    int                   `json:"total_attempts"`
}

// TeacherOverviewStatus defines model for TeacherOverview.Status.
type TeacherOverviewStatus string

// TeacherQuestion defines model for TeacherQuestion.
type TeacherQuestion struct {
	Body QuestionBody `json:"body"`

	// Correct The answer key. The option key (single), option keys (multi), a boolean (truefalse), or {accepted: [...]} (short). Owner-facing responses only.
	Correct  interface{}           `json:"correct"`
	Id       openapi_types.UUID    `json:"id"`
	Options  *[]QuestionOption     `json:"options,omitempty"`
	Points   float32               `json:"points"`
	Position int                   `json:"position"`
	QuizId   openapi_types.UUID    `json:"quiz_id"`
	Source   TeacherQuestionSource `json:"source"`

	// Topic Free-text topic tag, or null when the question is untagged. Tags are frozen into the version snapshot on publish and drive StudentStats.topic_strengths.
	Topic *string             `json:"topic"`
	Type  TeacherQuestionType `json:"type"`
}

// TeacherQuestionSource defines model for TeacherQuestion.Source.
type TeacherQuestionSource string

// TeacherQuestionType defines model for TeacherQuestion.Type.
type TeacherQuestionType string

// TeacherStats A teacher's activity-and-outcomes summary (docs/07 section 4), aggregated live rather than from a rollup table.
type TeacherStats struct {
	// AvgClassScore Mean of each quiz's raw-point mean; not a percentage.
	AvgClassScore          *float32           `json:"avg_class_score"`
	AvgParticipation       *float32           `json:"avg_participation"`
	AvgPublishToResultsSec *float32           `json:"avg_publish_to_results_sec"`
	QuizzesConducted       int                `json:"quizzes_conducted"`
	QuizzesCreated         int                `json:"quizzes_created"`
	TeacherId              openapi_types.UUID `json:"teacher_id"`
	TotalAttempts          int                `json:"total_attempts"`
}

// TeacherStudentPerformance One student's performance on a single teacher's quizzes - the teacher-scoped view of docs/07 section 3, one row per assigned student with a per-quiz breakdown.
type TeacherStudentPerformance struct {
	AssignedQuizzes int `json:"assigned_quizzes"`

	// AvgScorePercent Mean over completed quizzes of the best graded attempt's score as a percentage of the pinned snapshot's points.
	AvgScorePercent *float32 `json:"avg_score_percent"`

	// CompletedQuizzes Assigned quizzes with at least one graded attempt.
	CompletedQuizzes int        `json:"completed_quizzes"`
	Email            string     `json:"email"`
	FullName         string     `json:"full_name"`
	LastSubmittedAt  *time.Time `json:"last_submitted_at"`

	// Quizzes Per-quiz breakdown, title-ordered.
	Quizzes []struct {
		QuizId       openapi_types.UUID                     `json:"quiz_id"`
		ScorePercent *float32                               `json:"score_percent"`
		Status       TeacherStudentPerformanceQuizzesStatus `json:"status"`
		SubmittedAt  *time.Time                             `json:"submitted_at"`
		Title        string                                 `json:"title"`
	} `json:"quizzes"`
	StudentId openapi_types.UUID `json:"student_id"`

	// TotalViolations Guardrail violations across every attempt on this teacher's quizzes.
	TotalViolations int `json:"total_violations"`
}

// TeacherStudentPerformanceQuizzesStatus defines model for TeacherStudentPerformance.Quizzes.Status.
type TeacherStudentPerformanceQuizzesStatus string

// UpdateQuizRequest defines model for UpdateQuizRequest.
type UpdateQuizRequest struct {
	MaxAttempts      *int    `json:"max_attempts,omitempty"`
	ShuffleQuestions *bool   `json:"shuffle_questions,omitempty"`
	Title            *string `json:"title,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	FullName *string `json:"full_name,omitempty"`

	// ResetPassword Issue a fresh one-time credential and revoke all sessions.
	ResetPassword *bool                    `json:"reset_password,omitempty"`
	Status        *UpdateUserRequestStatus `json:"status,omitempty"`
}

// UpdateUserRequestStatus defines model for UpdateUserRequest.Status.
type UpdateUserRequestStatus string

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	FullName  string              `json:"full_name"`
	Id        openapi_types.UUID  `json:"id"`

	// MustChangePassword True while the account still uses its admin-issued credential; every endpoint except auth answers 403 PASSWORD_CHANGE_REQUIRED until the user sets their own password.
	MustChangePassword bool       `json:"must_change_password"`
	Role               UserRole   `json:"role"`
	Status             UserStatus `json:"status"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserStatus defines model for User.Status.
type UserStatus string

// UserImportError The Error envelope plus the roster import's per-row report, the synchronous sibling of Import.error_report.
type UserImportError struct {
	Code string `json:"code"`

	// Fields File-level problems (e.g. size, missing columns).
	Fields    *map[string]string `json:"fields,omitempty"`
	Message   string             `json:"message"`
	RowErrors *[]struct {
		Column  string `json:"column"`
		Message string `json:"message"`

		// Row 1-based data row number, header excluded.
		Row int `json:"row"`
	} `json:"row_errors,omitempty"`
}

// UserImportResult defines model for UserImportResult.
type UserImportResult struct {
	// Users The created accounts, in the file's row order.
	Users []ProvisionedUser `json:"users"`
}

// ViolationResponse defines model for ViolationResponse.
type ViolationResponse struct {
	// Attempt The student-facing attempt shape. The owner is always the caller and the score is withheld until the results-release policy lands with grading, so neither appears here.
	Attempt Attempt `json:"attempt"`

	// Counted Whether this report incremented violation_count (true only for a guardrail whose snapshotted policy is `count`).
	Counted bool `json:"counted"`
}

// ViolationTally One guardrail's logged violations for a single attempt.
type ViolationTally struct {
	// Count How many attempt.violation rows of this type were logged.
	Count int `json:"count"`

	// TotalDurationMs Summed duration of the reports that carried one - focus loss is the only guardrail that measures a span ("left the tab for 40 s"). Null for guardrails that report an instant.
	TotalDurationMs *int               `json:"total_duration_ms"`
	Type            ViolationTallyType `json:"type"`
}

// ViolationTallyType defines model for ViolationTally.Type.
type ViolationTallyType string

// AssignmentConflict defines model for AssignmentConflict.
type AssignmentConflict = Error

// AttemptConflict defines model for AttemptConflict.
type AttemptConflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotEditable defines model for NotEditable.
type NotEditable = Error

// NotFound defines model for NotFound.
type NotFound = Error

// QuizNotClosed defines model for QuizNotClosed.
type QuizNotClosed = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// ResultsNotReleased defines model for ResultsNotReleased.
type ResultsNotReleased = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Error

// ReportAttemptViolationJSONBody defines parameters for ReportAttemptViolation.
type ReportAttemptViolationJSONBody struct {
	// DurationMs Optional duration of the violation (e.g. focus-loss length).
	DurationMs *int `json:"duration_ms"`

	// Type The guardrail the violation is reported against.
	Type ReportAttemptViolationJSONBodyType `json:"type"`
}

// ReportAttemptViolationJSONBodyType defines parameters for ReportAttemptViolation.
type ReportAttemptViolationJSONBodyType string

// KickAttemptJSONBody defines parameters for KickAttempt.
type KickAttemptJSONBody struct {
	// Reason Why the student was removed (canned phrase plus optional free text).
	Reason string `json:"reason"`
}

// OverrideAttemptScoreJSONBody defines parameters for OverrideAttemptScore.
type OverrideAttemptScoreJSONBody struct {
	// Reason Why the score is being overridden (canned phrase plus optional free text).
	Reason string `json:"reason"`
}

// ReadmitAttemptJSONBody defines parameters for ReadmitAttempt.
type ReadmitAttemptJSONBody struct {
	// Reason Why the student is being readmitted (canned phrase plus optional free text).
	Reason string `json:"reason"`
}

// ListAuditLogParams defines parameters for ListAuditLog.
type ListAuditLogParams struct {
	// ActorId Only entries written by this account.
	ActorId *openapi_types.UUID `form:"actor_id,omitempty" json:"actor_id,omitempty"`

	// Action Exact action match, e.g. quizzes.published.
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// ResourceType Exact resource type, e.g. quiz, attempt, question.
	ResourceType *string `form:"resource_type,omitempty" json:"resource_type,omitempty"`

	// ResourceId Only entries touching this resource.
	ResourceId *openapi_types.UUID `form:"resource_id,omitempty" json:"resource_id,omitempty"`

	// From Inclusive lower bound on the entry time (at >= from).
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive upper bound on the entry time (at < to).
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Before Keyset cursor - return entries with id strictly below this.
	Before *int64 `form:"before,omitempty" json:"before,omitempty"`

	// Limit Page size, 1..200 (default 50).
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateGroupJSONBody defines parameters for CreateGroup.
type CreateGroupJSONBody struct {
	Name string `json:"name"`
}

// SetGroupMembersJSONBody defines parameters for SetGroupMembers.
type SetGroupMembersJSONBody struct {
	StudentIds []openapi_types.UUID `json:"student_ids"`
}

// CreateQuizJSONBody defines parameters for CreateQuiz.
type CreateQuizJSONBody struct {
	Title string `json:"title"`
}

// ExtendQuizJSONBody defines parameters for ExtendQuiz.
type ExtendQuizJSONBody struct {
	// EndsAt The new close time; must be in the future and later than the current ends_at.
	EndsAt time.Time `json:"ends_at"`
}

// ReorderQuestionsJSONBody defines parameters for ReorderQuestions.
type ReorderQuestionsJSONBody struct {
	QuestionIds []openapi_types.UUID `json:"question_ids"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Role   *ListUsersParamsRole   `form:"role,omitempty" json:"role,omitempty"`
	Status *ListUsersParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListUsersParamsRole defines parameters for ListUsers.
type ListUsersParamsRole string

// ListUsersParamsStatus defines parameters for ListUsers.
type ListUsersParamsStatus string

// SaveAnswerJSONRequestBody defines body for SaveAnswer for application/json ContentType.
type SaveAnswerJSONRequestBody = SaveAnswerRequest

// ReportAttemptViolationJSONRequestBody defines body for ReportAttemptViolation for application/json ContentType.
type ReportAttemptViolationJSONRequestBody ReportAttemptViolationJSONBody

// KickAttemptJSONRequestBody defines body for KickAttempt for application/json ContentType.
type KickAttemptJSONRequestBody KickAttemptJSONBody

// OverrideAttemptScoreJSONRequestBody defines body for OverrideAttemptScore for application/json ContentType.
type OverrideAttemptScoreJSONRequestBody OverrideAttemptScoreJSONBody

// ReadmitAttemptJSONRequestBody defines body for ReadmitAttempt for application/json ContentType.
type ReadmitAttemptJSONRequestBody ReadmitAttemptJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody CreateGroupJSONBody

// SetGroupMembersJSONRequestBody defines body for SetGroupMembers for application/json ContentType.
type SetGroupMembersJSONRequestBody SetGroupMembersJSONBody

// UpdateQuestionJSONRequestBody defines body for UpdateQuestion for application/json ContentType.
type UpdateQuestionJSONRequestBody = QuestionInput

// CreateQuizJSONRequestBody defines body for CreateQuiz for application/json ContentType.
type CreateQuizJSONRequestBody CreateQuizJSONBody

// UpdateQuizJSONRequestBody defines body for UpdateQuiz for application/json ContentType.
type UpdateQuizJSONRequestBody = UpdateQuizRequest

// SetAssignmentsJSONRequestBody defines body for SetAssignments for application/json ContentType.
type SetAssignmentsJSONRequestBody = SetAssignmentsRequest

// ExtendQuizJSONRequestBody defines body for ExtendQuiz for application/json ContentType.
type ExtendQuizJSONRequestBody ExtendQuizJSONBody

// PublishQuizJSONRequestBody defines body for PublishQuiz for application/json ContentType.
type PublishQuizJSONRequestBody = PublishQuizRequest

// AddQuestionJSONRequestBody defines body for AddQuestion for application/json ContentType.
type AddQuestionJSONRequestBody = QuestionInput

// ReorderQuestionsJSONRequestBody defines body for ReorderQuestions for application/json ContentType.
type ReorderQuestionsJSONRequestBody ReorderQuestionsJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest
