package analytics

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"

	"macquiz/server/internal/apischema"
	"macquiz/server/internal/authusers"
)

// This file owns the read side of Milestone 8 (docs/04 section 2:
// "GET /analytics/quizzes/:id - Quiz stats + item analysis (from
// quiz_stats)"). It serves the row that RollupDue computed on close; it never
// computes on read, so a dashboard hit is one cheap primary-key lookup.

// ErrNotFound is returned for a quiz the caller may not see, a quiz that does
// not exist, and a quiz whose stats have not been rolled up yet. All three
// collapse to one 404 at the edge so a non-owner can never tell a private
// quiz's existence from an authorization failure (docs/08 section 3).
var ErrNotFound = errors.New("analytics: not found")

// Service reads the analytics rollups. It stays inside the analytics boundary
// (docs/02 section 3): it only reads quiz_stats plus the quiz's owner for the
// authorization decision, and writes nothing.
type Service struct {
	db  *sql.DB
	log *slog.Logger
}

// NewService wires the analytics read service.
func NewService(db *sql.DB, log *slog.Logger) *Service {
	return &Service{db: db, log: log}
}

// QuizStats is the quiz_stats row shaped for the wire, built directly from
// the generated apischema.QuizStats type (api/openapi.yaml, generated by
// oapi-codegen - see internal/apischema) rather than a hand-written struct,
// so a spec change to this response can never silently drift from what this
// endpoint actually serializes. mean/median/participation are null-scored
// for a quiz no student completed.
type QuizStats = apischema.QuizStats

// float32ptr narrows a nullable float64 column to the *float32 the generated
// wire type expects. These fields are percentages/scores intended for
// display (docs/07 section 3), never a financial or precision-sensitive
// computation, so float32's ~7 significant digits lose nothing that matters
// on the wire.
func float32ptr(v sql.NullFloat64) *float32 {
	if !v.Valid {
		return nil
	}
	f := float32(v.Float64)
	return &f
}

// QuizStats returns one quiz's rolled-up stats for the owning teacher or an
// admin (docs/04 permission matrix: teacher analytics is self-only). It loads
// the quiz's owner first so the policy resolves admin-OR-owning-teacher, and
// maps every "you cannot see this" outcome - not authorized, unknown quiz, not
// yet rolled up - to ErrNotFound, mirroring quiz.Service.Results.
func (s *Service) QuizStats(ctx context.Context, actor authusers.User, quizID string) (QuizStats, error) {
	var ownerID string
	err := s.db.QueryRowContext(ctx,
		`SELECT owner_id::text FROM quizzes WHERE id = $1`, quizID).Scan(&ownerID)
	if err == sql.ErrNoRows {
		return QuizStats{}, ErrNotFound
	}
	if err != nil {
		return QuizStats{}, fmt.Errorf("load quiz owner: %w", err)
	}
	if !authusers.Can(actor, authusers.ActionAnalyticsTeacher,
		authusers.Resource{OwnerID: ownerID}) {
		return QuizStats{}, ErrNotFound
	}

	quizUUID, err := uuid.Parse(quizID)
	if err != nil {
		return QuizStats{}, ErrNotFound
	}

	var distribution, itemAnalysis, integrity []byte
	var mean, median, participation sql.NullFloat64
	out := QuizStats{QuizId: quizUUID}
	err = s.db.QueryRowContext(ctx,
		`SELECT distribution, mean, median, participation, item_analysis, integrity, computed_at
		 FROM quiz_stats WHERE quiz_id = $1`, quizID).Scan(
		&distribution, &mean, &median, &participation,
		&itemAnalysis, &integrity, &out.ComputedAt)
	if err == sql.ErrNoRows {
		// The quiz exists and the caller may see it, but the rollup has not run
		// yet (the quiz is still open, or it just closed and the sweep has not
		// reached it). Report the same 404 - there is nothing to show.
		return QuizStats{}, ErrNotFound
	}
	if err != nil {
		return QuizStats{}, fmt.Errorf("load quiz_stats: %w", err)
	}
	out.Mean = float32ptr(mean)
	out.Median = float32ptr(median)
	out.Participation = float32ptr(participation)
	if err := json.Unmarshal(distribution, &out.Distribution); err != nil {
		return QuizStats{}, fmt.Errorf("decode distribution: %w", err)
	}
	if err := json.Unmarshal(itemAnalysis, &out.ItemAnalysis); err != nil {
		return QuizStats{}, fmt.Errorf("decode item_analysis: %w", err)
	}
	if err := json.Unmarshal(integrity, &out.Integrity); err != nil {
		return QuizStats{}, fmt.Errorf("decode integrity: %w", err)
	}
	return out, nil
}

// StudentStats is the student_stats row shaped for the wire, built directly
// from the generated apischema.StudentStats type rather than a hand-written
// struct (see QuizStats). avg_time_per_question and completion_rate are null
// for a student who has never had a quiz close over them.
type StudentStats = apischema.StudentStats

// StudentStats returns one student's cross-quiz performance profile
// (docs/04 permission matrix: a student sees only themselves, a teacher sees
// their assigned students, an admin sees all). The audience test is the only
// fact Can needs beyond the actor: for a teacher it is whether the subject is
// assigned to any quiz the teacher owns, resolved with one EXISTS query; admin
// and student never consult it. Every "you cannot see this" outcome - not
// authorized, unknown student, not yet rolled up - collapses to ErrNotFound so
// a caller can never tell one student's existence from an authorization
// failure (docs/08 section 3), mirroring QuizStats.
func (s *Service) StudentStats(ctx context.Context, actor authusers.User, studentID string) (StudentStats, error) {
	assigned := false
	if actor.Role == "teacher" {
		if err := s.db.QueryRowContext(ctx,
			`SELECT EXISTS (
			   SELECT 1 FROM quiz_assignments a
			   JOIN quizzes q ON q.id = a.quiz_id
			   WHERE q.owner_id = $1 AND a.student_id = $2)`,
			actor.ID, studentID).Scan(&assigned); err != nil {
			return StudentStats{}, fmt.Errorf("check assignment: %w", err)
		}
	}
	if !authusers.Can(actor, authusers.ActionAnalyticsStudent,
		authusers.Resource{OwnerID: studentID, Assigned: assigned}) {
		return StudentStats{}, ErrNotFound
	}

	studentUUID, err := uuid.Parse(studentID)
	if err != nil {
		return StudentStats{}, ErrNotFound
	}

	out := StudentStats{StudentId: studentUUID}
	var accuracyTrend, topicStrengths []byte
	var avgTimePerQuestion, completionRate sql.NullFloat64
	err = s.db.QueryRowContext(ctx,
		`SELECT accuracy_trend, avg_time_per_question, completion_rate, topic_strengths, updated_at
		 FROM student_stats WHERE student_id = $1`, studentID).Scan(
		&accuracyTrend, &avgTimePerQuestion, &completionRate, &topicStrengths, &out.UpdatedAt)
	if err == sql.ErrNoRows {
		// The caller may see this student, but no quiz has closed over them yet
		// (or the id is not a student at all). Same 404 - nothing to show.
		return StudentStats{}, ErrNotFound
	}
	if err != nil {
		return StudentStats{}, fmt.Errorf("load student_stats: %w", err)
	}
	out.AvgTimePerQuestion = float32ptr(avgTimePerQuestion)
	out.CompletionRate = float32ptr(completionRate)
	if err := json.Unmarshal(accuracyTrend, &out.AccuracyTrend); err != nil {
		return StudentStats{}, fmt.Errorf("decode accuracy_trend: %w", err)
	}
	if err := json.Unmarshal(topicStrengths, &out.TopicStrengths); err != nil {
		return StudentStats{}, fmt.Errorf("decode topic_strengths: %w", err)
	}
	return out, nil
}

// TeacherStats is a teacher's activity-and-outcomes summary for the wire
// (docs/07 section 4, "Per teacher"). Unlike QuizStats and StudentStats it
// reads no rollup table - there is no teacher_stats - so it aggregates live
// from quizzes, attempts, and the per-quiz quiz_stats rows each close froze.
// The averages are null for a teacher whose quizzes have no rolled-up stats
// yet (or who has released no results), never for a real-but-idle teacher, who
// reports zero counts.
// AvgClassScore is the mean of each rolled-up quiz's mean, which quiz_stats
// stores in raw points; every fixture quiz is out of 10 here, but averaging
// raw points across quizzes of differing max scores is points-not-percent by
// design - quiz_stats keeps no percentage mean to average instead.
type TeacherStats = apischema.TeacherStats

// TeacherStats returns one teacher's activity-and-outcomes summary for an admin
// or that teacher themselves (docs/07 section 4: teacher analytics are
// admin-only; a teacher sees their own). Authorization runs first via
// ActionAnalyticsTeacher with the subject as owner - a teacher can only ever
// pass it for their own id, so they can never probe another's - then an
// explicit "is this id a teacher" check 404s an admin aiming at a student or an
// unknown id. That existence check is what lets a real-but-idle teacher return
// zero counts (a legitimate 200) while keeping every "you cannot see this"
// outcome an existence-safe ErrNotFound, mirroring QuizStats.
func (s *Service) TeacherStats(ctx context.Context, actor authusers.User, teacherID string) (TeacherStats, error) {
	if !authusers.Can(actor, authusers.ActionAnalyticsTeacher,
		authusers.Resource{OwnerID: teacherID}) {
		return TeacherStats{}, ErrNotFound
	}
	var isTeacher bool
	if err := s.db.QueryRowContext(ctx,
		`SELECT EXISTS (SELECT 1 FROM users WHERE id = $1 AND role = 'teacher')`,
		teacherID).Scan(&isTeacher); err != nil {
		return TeacherStats{}, fmt.Errorf("check teacher: %w", err)
	}
	if !isTeacher {
		return TeacherStats{}, ErrNotFound
	}

	teacherUUID, err := uuid.Parse(teacherID)
	if err != nil {
		return TeacherStats{}, ErrNotFound
	}

	// One round trip: counts of created (all owned) and conducted (launched -
	// published_at set) quizzes, every attempt across them, the averages of the
	// frozen per-quiz participation and mean, and the mean publish-to-results
	// latency in seconds over quizzes whose results have actually been released.
	out := TeacherStats{TeacherId: teacherUUID}
	var avgParticipation, avgClassScore, avgPublishToResultsSec sql.NullFloat64
	err = s.db.QueryRowContext(ctx,
		`SELECT
		   (SELECT count(*) FROM quizzes WHERE owner_id = $1),
		   (SELECT count(*) FROM quizzes WHERE owner_id = $1 AND published_at IS NOT NULL),
		   (SELECT count(*) FROM attempts a JOIN quizzes q ON q.id = a.quiz_id WHERE q.owner_id = $1),
		   (SELECT avg(qs.participation) FROM quiz_stats qs JOIN quizzes q ON q.id = qs.quiz_id WHERE q.owner_id = $1),
		   (SELECT avg(qs.mean) FROM quiz_stats qs JOIN quizzes q ON q.id = qs.quiz_id WHERE q.owner_id = $1),
		   (SELECT extract(epoch FROM avg(results_released_at - published_at))
		      FROM quizzes WHERE owner_id = $1 AND results_released_at IS NOT NULL AND published_at IS NOT NULL)`,
		teacherID).Scan(
		&out.QuizzesCreated, &out.QuizzesConducted, &out.TotalAttempts,
		&avgParticipation, &avgClassScore, &avgPublishToResultsSec)
	if err != nil {
		return TeacherStats{}, fmt.Errorf("aggregate teacher stats: %w", err)
	}
	out.AvgParticipation = float32ptr(avgParticipation)
	out.AvgClassScore = float32ptr(avgClassScore)
	out.AvgPublishToResultsSec = float32ptr(avgPublishToResultsSec)
	return out, nil
}

// CohortStats compares one group's members against the platform-wide
// student-analytics profile (docs/07 section 4, "cohort comparisons across
// groups"). AvgCompletionRate and AvgAccuracy are null when no member has a
// student_stats rollup yet, mirroring the per-student null-until-rolled-up
// convention.
type CohortStats = apischema.CohortStats

// OrgStats is the admin org-wide dashboard (docs/07 section 4, FR-9): active
// users, a recent quizzes-created trend, platform-wide participation, and a
// per-group cohort comparison. Unlike QuizStats/StudentStats it has no
// rollup table of its own - every field is computed live from small,
// already-indexed aggregates (user/group counts, the frozen per-quiz
// quiz_stats rows), so it stays cheap without needing a dedicated org_stats
// table. Built directly from the generated apischema.OrgStats type, same as
// the other analytics responses.
type OrgStats = apischema.OrgStats

// OrgStats returns the org-wide dashboard for an admin (docs/04 permission
// matrix: org analytics is admin-only, so the caller gates on ActionAnalyticsOrg
// before this ever runs; there is no per-resource decision left to make here).
func (s *Service) OrgStats(ctx context.Context, actor authusers.User) (OrgStats, error) {
	if !authusers.Can(actor, authusers.ActionAnalyticsOrg, authusers.Resource{}) {
		return OrgStats{}, ErrNotFound
	}

	var out OrgStats
	out.QuizzesPerWeek = []struct {
		Count     int       `json:"count"`
		WeekStart time.Time `json:"week_start"`
	}{}
	out.CohortComparisons = []CohortStats{}
	var platformParticipation sql.NullFloat64
	err := s.db.QueryRowContext(ctx,
		`SELECT
		   (SELECT count(*) FROM users WHERE role = 'admin' AND status = 'active'),
		   (SELECT count(*) FROM users WHERE role = 'teacher' AND status = 'active'),
		   (SELECT count(*) FROM users WHERE role = 'student' AND status = 'active'),
		   (SELECT avg(participation) FROM quiz_stats)`,
	).Scan(&out.ActiveUsers.Admins, &out.ActiveUsers.Teachers, &out.ActiveUsers.Students,
		&platformParticipation)
	if err != nil {
		return OrgStats{}, fmt.Errorf("load org headcounts: %w", err)
	}
	out.PlatformParticipation = float32ptr(platformParticipation)

	// Last 12 weeks of quiz creation, oldest first; a week with no quizzes is
	// simply absent (the dashboard renders it as a zero bucket), matching the
	// sparse-series convention student_stats.accuracy_trend already uses.
	rows, err := s.db.QueryContext(ctx,
		`SELECT date_trunc('week', created_at) AS week_start, count(*)
		 FROM quizzes
		 WHERE created_at >= date_trunc('week', now()) - interval '11 weeks'
		 GROUP BY week_start
		 ORDER BY week_start`)
	if err != nil {
		return OrgStats{}, fmt.Errorf("load quizzes per week: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var wc struct {
			Count     int       `json:"count"`
			WeekStart time.Time `json:"week_start"`
		}
		if err := rows.Scan(&wc.WeekStart, &wc.Count); err != nil {
			return OrgStats{}, fmt.Errorf("scan weekly count: %w", err)
		}
		out.QuizzesPerWeek = append(out.QuizzesPerWeek, wc)
	}
	if err := rows.Err(); err != nil {
		return OrgStats{}, fmt.Errorf("load quizzes per week: %w", err)
	}

	// One row per group, each member's completion_rate averaged directly and
	// each member's own average accuracy (across their accuracy_trend) averaged
	// via a lateral subquery, since accuracy lives one level deeper than
	// completion_rate inside the jsonb trend array.
	cohortRows, err := s.db.QueryContext(ctx,
		`SELECT g.id::text, g.name, count(gm.student_id),
		        avg(ss.completion_rate)::float8, avg(sub.avg_accuracy)
		 FROM groups g
		 LEFT JOIN group_members gm ON gm.group_id = g.id
		 LEFT JOIN student_stats ss ON ss.student_id = gm.student_id
		 LEFT JOIN LATERAL (
		     SELECT avg((elem->>'accuracy')::float8) AS avg_accuracy
		     FROM jsonb_array_elements(ss.accuracy_trend) elem
		     WHERE elem->>'accuracy' IS NOT NULL
		 ) sub ON true
		 GROUP BY g.id, g.name
		 ORDER BY g.name`)
	if err != nil {
		return OrgStats{}, fmt.Errorf("load cohort comparisons: %w", err)
	}
	defer cohortRows.Close()
	for cohortRows.Next() {
		var groupID string
		var cs CohortStats
		var avgCompletionRate, avgAccuracy sql.NullFloat64
		if err := cohortRows.Scan(&groupID, &cs.GroupName, &cs.MemberCount,
			&avgCompletionRate, &avgAccuracy); err != nil {
			return OrgStats{}, fmt.Errorf("scan cohort stats: %w", err)
		}
		cs.GroupId, err = uuid.Parse(groupID)
		if err != nil {
			return OrgStats{}, fmt.Errorf("parse cohort group id: %w", err)
		}
		cs.AvgCompletionRate = float32ptr(avgCompletionRate)
		cs.AvgAccuracy = float32ptr(avgAccuracy)
		out.CohortComparisons = append(out.CohortComparisons, cs)
	}
	if err := cohortRows.Err(); err != nil {
		return OrgStats{}, fmt.Errorf("load cohort comparisons: %w", err)
	}
	return out, nil
}
